# Generated by Django 3.0.3 on 2020-03-04 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punter', models.CharField(max_length=200)),
                ('bet_date', models.DateField(default=django.utils.timezone.now)),
                ('bet_year', models.PositiveIntegerField(default=2019)),
                ('bet_week', models.PositiveIntegerField()),
                ('bet_number', models.PositiveIntegerField()),
                ('bet_legs', models.PositiveIntegerField()),
                ('bet_amount', models.FloatField(default=0.0)),
                ('bet_event', models.CharField(max_length=200)),
                ('bet_odds', models.FloatField(default=0.0)),
                ('bet_win', models.BooleanField()),
                ('bet_potential', models.FloatField(default=0.0)),
                ('bet_cashed', models.BooleanField()),
                ('bet_return', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['bet_date', 'punter', 'bet_number'],
            },
        ),
        migrations.CreateModel(
            name='Multi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_leg', models.PositiveIntegerField()),
                ('bet_type', models.CharField(max_length=200)),
                ('bet_team', models.CharField(max_length=200)),
                ('bet_opposition', models.CharField(max_length=200)),
                ('bet_home', models.BooleanField()),
                ('bet_odds', models.FloatField()),
                ('bet_win', models.BooleanField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASPC.Parent')),
            ],
        ),
    ]
