# Generated by Django 3.0.3 on 2020-03-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASPC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Punter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('week', models.PositiveIntegerField()),
            ],
        ),
    ]
