# Generated by Django 3.0.3 on 2020-03-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASPC', '0002_hits_punter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hits',
            new_name='Hit',
        ),
    ]
